services:
  frontend:
    container_name: openmemory-ui
    build:
      context: .
      dockerfile: Dockerfile
    image: mem0/openmemory-ui:latest
    ports:
      - "${OPENMEMORY_UI_PORT:-3000}:3000"
    env_file:
      - .env
    environment:
      - PORT={OPENMEMORY_UI_PORT:-3000}
      - NEXT_PUBLIC_API_URL=http://${OPENMEMORY_API_HOST:-host.docker.internal}:${OPENMEMORY_API_PORT:-8765}
      - NEXT_PUBLIC_USER_ID=${OPENMEMORY_USER:-default_user}
