services:
  api:
    image: mem0/openmemory-mcp
    build: .
    environment:
      - OPENAI_API_KEY
      - USER
      - QDRANT_HOST=host.docker.internal
      - QDRANT_PORT=6333
      - OLLAMA_NO_INTERACTIVE=1
    env_file:
      - .env
    ports:
      - "8765:8765"
    volumes:
      - memories:/usr/src/openmemory
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  memories:
