services:
  api:
    image: mem0/openmemory-mcp
    build: .
    environment:
      - OPENAI_API_KEY
      - USER
      - QDRANT_HOST=host.docker.internal
      - QDRANT_PORT=6333
      - OLLAMA_NO_INTERACTIVE=1
    env_file:
      - .env
    ports:
      - "8765:8765"
    volumes:
      - .:/usr/src/openmemory
    extra_hosts:
      - "host.docker.internal:host-gateway"
    command: >
      sh -c "bash /usr/src/openmemory/install_ollama.sh && uvicorn main:app --host 0.0.0.0 --port 8765 --reload --workers 4"
