services:
  api:
    container_name: openmemory-api
    image: mem0/openmemory-mcp
    build: .
    environment:
      - OPENROUTER_API_KEY=${OPENROUTER_API_KEY}
      - USER=${OPENMEMORY_USER}
      - QDRANT_HOST=http://localhost
      - QDRANT_PORT=6333
      - OLLAMA_NO_INTERACTIVE=1
    env_file:
      - .env
    ports:
      - "${OPENMEMORY_API_PORT:-8765}:8765"
    volumes:
      - memories:/usr/src/openmemory
    networks:
      - proxy

volumes:
  memories:

networks:
  proxy:
    external: true
